kiali:
  # This is required for "openshift" auth strategy.
  # You have to know ahead of time what your Route URL will be because
  # right now the helm chart can't figure this out at runtime (it would
  # need to wait for the Kiali Route to be deployed and for OpenShift
  # to start it up). If someone knows how to update this helm chart to
  # do this, a PR would be welcome.
  kiali_route_url: ""

  #
  # Settings that mimic the Kiali CR which are placed in the ConfigMap.
  # Note that only those values used by the Helm Chart will be here.
  #

  istio_namespace: "istio-system" # default is where Kiali is installed

  auth:
    strategy: openshift
  deployment:
    accessible_namespaces:
      - "**"
    image_pull_policy: ''
    ingress:
      enabled: true
    pod_labels:
      sidecar.istio.io/inject: 'false'
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    logger:
      log_level: debug

  external_services:
    custom_dashboards:
      namespace_label: kubernetes_namespace
    # grafana:
    #   auth:
    #     password: {{ .Values.htpasswd }}
    #     type: none
    #     use_kiali_token: false
    #     username: internal
    #   enabled: true
    #   in_cluster_url: 'http://grafana-instance-service.istio-system.svc:3000'
    #   url: {{ .Values.kiali.grafana.url }}
    istio:
      config_map_name: istio
      istio_sidecar_injector_config_map_name: istio-sidecar-injector
      istiod_deployment_name: istiod
      url_service_version: 'http://istiod.istio-system:15014/version'
    prometheus:
      auth:
        insecure_skip_verify: true
      #   type: bearer
      #   use_kiali_token: true
      # query_scope:
      #   mesh_id: istio-system/full-install
      url: 'http://prometheus.istio-monitoring.svc.cluster.local:9090'
    # tracing:
    #   auth:
    #     password: {{ .Values.htpasswd }}
    #     type: basic
    #     use_kiali_token: false
    #     username: internal
    #   enabled: true
    #   in_cluster_url: http://jaeger-query-internal.istio-system.svc.cluster.local
    #   namespace: istio-system
    #   service: ''
    #   url: {{ .Values.kiali.jaeger.url }}
    #   use_grpc: false
