{
 "title": "adaptive",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "min rtt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "envoy_http_inbound_0_0_0_0_9080_adaptive_concurrency_gradient_controller_min_rtt_msecs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(envoy_http_inbound_0_0_0_0_9080_adaptive_concurrency_gradient_controller_rq_blocked[5m])) by (pod, namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "burst queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "envoy_http_inbound_0_0_0_0_9080_adaptive_concurrency_gradient_controller_burst_queue_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "concurrency limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "envoy_http_inbound_0_0_0_0_9080_adaptive_concurrency_gradient_controller_concurrency_limit ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}